### ISSUE TITLE
Drag nodes with mouse

### ISSUE THREAD

**Issue by jmigual** [jrfonseca/xdot.py#115]
Would it be possible to add the functionality to drag nodes with the mouse? 

Sometimes some nodes or edges overlap, and it'd be useful to move them around just to visualize them.

**Comment by jrfonseca** [comment]
No, I'm afraid this is not practical.  The node layout is wholly controlled by GraphViz.  There's no way for `xdot.py` to control node placement, and even if there was, other nodes might move radically position.
