### ISSUE TITLE
Compatibility with python 3.12

### ISSUE THREAD

**Issue by fsimonis** [jrfonseca/xdot.py#125]
Ubuntu 24.04 LTS, Fedora 39/40 and Arch are using/have moved to python 3.12, which removes the `distutils` package. 

This means that xdot requires https://github.com/jrfonseca/xdot.py/commit/86941185517181a153d3b80d984ec64ecba8c69a to be functional for those distros. Consequently, xdot and depending projects are currently blocked on those distros.

Given that the problem has already been patched, @jrfonseca would you be so kind and create a new PyPi release of the current state? :pray:

**Comment by jrfonseca** [comment]
Done -- https://pypi.org/project/xdot/1.4/ .  Thanks for the friendly nudge!
