### ISSUE TITLE
XDot loops on incomplete file

### ISSUE THREAD

**Issue by wolfbjoe** [jrfonseca/xdot.py#21]
Thank you for this wonderful application! XDot does a great job when displaying dot files and helps a lot when creating dot files manually.

However, if the dot file contains errors, XDot sometimes loops.

In some situations, the parser apparently expects a token of a certain type even after having reached EOF.

Attached you'll find two "buggy" input files causing XDot to hang, plus a tiny patch, which I am using.

Thanks & KR
Björn

[buggy_files_plus_patch.zip](https://github.com/jrfonseca/xdot.py/files/69739/buggy_files_plus_patch.zip)

**Comment by jrfonseca** [comment]
Patch pushed. Thanks!
