### ISSUE TITLE
Make a 0.7 release

### ISSUE THREAD

**Issue by abustany** [jrfonseca/xdot.py#24]
Could you consider making a 0.7 release? That way, changes like GTK3 xdot 1.7 support could be picked up by distributions.

Thanks :)

**Comment by jrfonseca** [comment]
Done.

**Comment by abustany** [comment]
Excellent, thanks a lot!

**Comment by Stebalien** [comment]
Could you please tag this release? Thanks.

**Comment by jrfonseca** [comment]
Completely forgot.  Tagged now.
