### ISSUE TITLE
Allow rendering from stdin without using a -

### ISSUE THREAD

**Issue by Stebalien** [jrfonseca/xdot.py#25]
Before 0.7, I was able to pipe a dot file to xdot to render it by running `something | xdot`. Now, I have to run `something | xdot -`. This isn't really a problem per-say, it's just a bit inconsistent with other unix commands where the `-` is optional if unambiguous.

**Comment by jrfonseca** [comment]
I agree it would be nice, but see issue #14.

If you find a reliable way of doing what you ask, while still avoiding issue #14, please reopen.  But it's not obvious for me what else can be done.

Requiring `-` seems to be the best compromise.  It's just two chars..

**Comment by Stebalien** [comment]
Good point. It just surprised me a bit when I upgraded to 0.7.
