### ISSUE TITLE
Split into multiple modules

### ISSUE THREAD

**Issue by Stebalien** [jrfonseca/xdot.py#29]
This obviously isn't very pressing but having one big python file makes it somewhat hard to work on xdot. I'd suggest a layout like the following:

```
.
├── dot
│   ├── __init__.py
│   ├── lexer.py
│   └── parser.py
├── __init__.py
└── ui
    ├── animations.py
    ├── colors.py
    ├── __init__.py
    ├── util.py
    └── window.py
```

**Comment by jrfonseca** [comment]
Sounds good in principle.  This could be also useful for #9.

But I'm afraid I don't have time to groom xdot.  (It works fine as is and I have lots of other projects demanding my attention.)

If you can propose a patch that does the above (and such that setup.py still works), then I'll happily commit.

**Comment by ZedThree** [comment]
I've made an attempt at doing this. I've also fixed a bunch of things highlighted by pyflakes/flake8, etc.
I've broadly followed @Stebalien's scheme above. `xdot/__main__.py` now contains the main GUI, everything else is split out into separate files.

Hopefully with this done, it will be possible to work on #9 as well :)

**Comment by ZedThree** [comment]
I import `DotWidget` and `DotWindow` at the top-level (i.e. so they're accessible as `xdot.DotWindow`) so as not to break the Travis test (and `sample.py`), as I assume these are the classes used the most. Currently things like `DotParser` are accessible through `xdot.dot.parser.DotParser` which is maybe a bit long. Any suggestions on which level various classes should be accessible?

**Comment by jrfonseca** [comment]
Now fiex thanks to @ZedThree
