### ISSUE TITLE
xdot can be installed on python 2.7 through pip (but it doesn't work)

### ISSUE THREAD

**Issue by ppolewicz** [jrfonseca/xdot.py#31]
to fix this, 'classifiers' should be set in `setup.py` (like [this](https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/setup.py#L57))

Also, dependency from `gi` and `gi-cairo` should be added so installation via pip is easier.

**Comment by ppolewicz** [comment]
Also, installation on Ubuntu now is simply `sudo apt-get install xdot`

**Comment by jrfonseca** [comment]
> 'classifiers' should be set in setup.py

Fixed. Thanks!

> Also, dependency from gi and gi-cairo should be added so installation via pip is easier.

I don't thing that installing gi and gi-cairo via pip works reliably, neither on Linux neither on Windows. It doesn't work for me at least

>  installation on Ubuntu now is simply sudo apt-get install xdot

Right. But I don't want to clutter the README with instructions of how to install xdot using every Linux distro out there.  I presume that people are confortable searching and installing packages using whatever Linux distro of their choice.
