### ISSUE TITLE
cross-compatibility with python2

### ISSUE THREAD

**Issue by anthraxx** [jrfonseca/xdot.py#33]
Hey,
It seems like with the 0.7 release this has became a python3 only library, however this breaks compatibility with applications that require python2.
It would be great if this library could work in a compatible way for both python versions. Using 0.6 for python2 applications may not a good option because of the way distribution level of packaging works. It would be awesome if this library could just work for both versions of python (looking at the python2-to-3 changes this may not be too hard to achieve).

**Comment by jrfonseca** [comment]
As explained in the README I don't have time for development.  (I barely have time for basica maintainance.)

I might consider patches for dual Python 2/3 support if anybody is willing to step up.  It must include updating `.travis.yml` to ensure code is tested both with Python 2 and 3.

**Comment by anthraxx** [comment]
sure, I can help you out with a patch once I have bit more time. Will create a pull request then and reference this issue in it.
