### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by plestrin** [jrfonseca/xdot.py#39]
https://github.com/jrfonseca/xdot.py/blob/a415018e00e8feb8828486a115a2ad42531faab1/xdot/dot/parser.py#L490

**Comment by jrfonseca** [comment]
Could you provide me a sample input that triggers this?

**Comment by plestrin** [comment]
Very basic stuff such as:
`graph {1 -- 2;}`

**Comment by jrfonseca** [comment]
Ouch.  Indeed https://travis-ci.org/jrfonseca/xdot.py shows this error all over the place, but somehow it didn't actually cause a failure to be reported..!

I need to fix the tests first.

**Comment by jrfonseca** [comment]
Ok.  It should be fixed now.  Thanks for reporting.
