### ISSUE TITLE
ImportError: No module named 'gi'

### ISSUE THREAD

**Issue by s9gf4ult** [jrfonseca/xdot.py#42]
1. successfully install via `pip install --user xdot` 
2. run `xdot` 

expected: 
opened empty xdot window 

actual: 

```
% xdot 
Traceback (most recent call last):
  File "/home/razor/.local/bin/xdot", line 11, in <module>
    load_entry_point('xdot==0.7', 'gui_scripts', 'xdot')()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/razor/.local/lib64/python3.4/site-packages/xdot.py", line 33, in <module>
    from gi.repository import GLib
ImportError: No module named 'gi'
```

**Comment by s9gf4ult** [comment]
PS. pygtk is installed.

**Comment by jrfonseca** [comment]
pygtk is for python2.  Python3 doesn't use pygtk.  See in https://github.com/jrfonseca/xdot.py/blob/master/README.md#debianubuntu-users the packages for debian/ubuntu. I'm not sure the package names for other Distros.

**Comment by s9gf4ult** [comment]
Ok. in gentoo this is just `dev-python/pygobject:3` package. I have just intalled and xdot works.

**Comment by Flurrywinde** [comment]
I am on Ubuntu 18.04, and after running the apt-get command here: https://github.com/jrfonseca/xdot.py/blob/master/README.md#debianubuntu-users , I still got the "No module named 'gi'" error.

I had to also run: `pip3 install PyGObject`. (Others may need to follow the complete instructions here: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started )

**Comment by jrfonseca** [comment]
@Flurrywinde that's surprising.  I was using Ubuntu 18.04 when I wrote those instructions, and Travis CI on https://github.com/jrfonseca/xdot.py/blob/master/.travis.yml is actually installing those packages on Ubuntu 18.04 bionic, testing it regularly.

Could it be that you're using a python virtual environment (eg., `virtualenv` or `pyenv`)?  Or have `python3` pointing to something other than the default python version?

**Comment by Flurrywinde** [comment]
Ah, yes, that must be what it was. I'm using `anaconda`.

**Comment by Dragorn421** [comment]
I'm under Kubuntu 22.04

I also had a "can't import gi" error, despite installing required packages through apt as requested.
Tried within an upgraded venv and outside.

I eventually noticed I could get xopt from `apt install xdot` and that worked then
