### ISSUE TITLE
Source ID was not found when attempting to remove it

### ISSUE THREAD

**Issue by code-hunger** [jrfonseca/xdot.py#44]
I get this warning when moving the image around and click on the nodes:
`/usr/lib/python3.6/site-packages/xdot.py:1326: Warning: Source ID 3747 was not found when attempting to remove it
`

**Comment by code-hunger** [comment]
I just found how this issue was resolved in another repository:
https://github.com/matplotlib/matplotlib/commit/5467c986bf79cd493248559a477a214a59201f51#diff-863ad36cddbe6c97d03668ddd129a3d0R211

I did the same to the Animation class and it worked. I'll send a pull request soon.

**Comment by code-hunger** [comment]
Turns out there's no problem with the git repository, only the archlinux one. #43 is not aplicable, too. Seems the PKGBUILD needs to be updated. I flagged the package out of date.

**Comment by jrfonseca** [comment]
Closing then.  Thanks.

**Comment by anthraxx** [comment]
The PKGBUILD is up to date as it points to the latest release, at some point a release should be made containing the fixes for the warning so they will get pulled into the distros.

**Comment by jrfonseca** [comment]
I see.  Yes, I tend to neglect doing releases as most around me use the master.  I'll reopen and make a new release then.

**Comment by anthraxx** [comment]
@jrfonseca cool, thanks :smile_cat:

**Comment by jrfonseca** [comment]
Version 0.8 is on PyPI: https://pypi.python.org/pypi/xdot/0.8
