### ISSUE TITLE
Maintenance of xdot.py

### ISSUE THREAD

**Issue by chdemko** [jrfonseca/xdot.py#55]
@jrfonseca We have read in your README file that you don't have time to maintain this package and that you want to delegate the code to someone else. Is it still the case?

**Comment by jrfonseca** [comment]
Yes, that's correct.  I've been doing the bare minimum for quite some time.

Do you use xdot.py extensively yourself?

**Comment by chdemko** [comment]
Not yet, but we worked on lattices in research and we want a library able to draw them.

**Comment by jrfonseca** [comment]
Yep. I can't guarantee I'll be responsive in the future.

**Comment by chdemko** [comment]
Ok thanks. We will contact you if we can maintain your work. Cheers
