### ISSUE TITLE
Request: don't recenter on reload?

### ISSUE THREAD

**Issue by bredelings** [jrfonseca/xdot.py#56]
Hi,

When I make a change to the dot file xdot is viewing, xdot reloads the file and then recenters.  So every time I change anything I have to manually locate the parent of the changed node.

This could be difficult to do perfectly, but if dot could pick a node in the viewpoint and try to make sure that node is viewable when a reload is performed, then this would make editing and viewing DOT files a lot easier!

**Comment by jrfonseca** [comment]
I agree this would be useful. I'd accept a patch, but I'm afraid I don't have the time/urge to do it myself.

**Comment by bredelings** [comment]
I may take a while, but will look into how this might be done.
