### ISSUE TITLE
xdot doesn't work~

### ISSUE THREAD

**Issue by airhuman** [jrfonseca/xdot.py#58]
Hello.
I've just installed xdot by using
`brew install xdot`

But when I start xdot from command line, it goes wrong.
![xdot_wrong](https://user-images.githubusercontent.com/1021047/40602771-6686aba2-628c-11e8-8fda-63fb4e764877.png)

Did I do sth wrong?
Please help, thank you~

**Comment by ildar** [comment]
Hi
IMHO the errors aren't fatal and your screenshot confesses that the program
is running. Did the window appear?

**Comment by jrfonseca** [comment]
In theory xdot should work on macOS given all its dependencies are cross platform.  But it's possible in practice things don't go that well.  In particular I don't know how robust GTK is on macOS, nor its Python bindings  At any rate, I'm unable to support/troubleshot macOS.

From googling, this sounds somewhat similar to  https://github.com/Homebrew/homebrew-core/issues/19187 , which was supposedly fixed.

I think your best bet is to reach to homebrew community.

**Comment by PangLuo** [comment]
Hi airhuman. Running "brew install adwaita-icon-theme" will fix your issue. I guess adwaita-icon-theme should be listed as required in README.

**Comment by jrfonseca** [comment]
xdot.py only uses stock icons, so I doubt any particular icon theme is necessary.  But otherwise you're right, _a_ icon theme is necessary.  Still, I'd expect this would be provided automatically by the package system, as a dependency of GTK itself.

**Comment by airhuman** [comment]
"brew install adwaita-icon-theme"  works~

Thank you.
