### ISSUE TITLE
Input from standard input doesn't work (on Linux)

### ISSUE THREAD

**Issue by zxgio** [jrfonseca/xdot.py#60]
I think that. in `__main.py__` the line:
            `win.set_dotcode(sys.stdin.read())`
should be:
           ` win.set_dotcode(sys.stdin.buffer.read())`
because it expects a byte string. See https://docs.python.org/3/library/sys.html#sys.stdin where the note says 

> To write or read binary data from/to the standard streams, use the underlying binary buffer object.

**Comment by jrfonseca** [comment]
@zxgio, @coroa, Thanks.

**Comment by mgedmin** [comment]
@jrfonseca could you make a bugfix release to PyPI please?  This bug is very annoying.

**Comment by jrfonseca** [comment]
No luck -- https://travis-ci.org/jrfonseca/xdot.py/builds/427718100 -- it will take me a bit longer.

**Comment by mgedmin** [comment]
Oh yeah, that doesn't look fun!

(I was always curious: people who rely on CI builds out of tags to make releases, how do they deal with release process failures?  Bump version and make a new tag?  Do the release manually Just This Once(TM)?)

**Comment by jrfonseca** [comment]
I often do `git push -f` to force a new tag.  Indeed I ended up doing a manual release.  The reason I didn't do it immedaitely is that not all my machines are setup with pypi credentials and what not.  At any rate it's done now.

**Comment by PangLuo** [comment]
Thank you! I'm new to this library. From the code I can see that even if no input file is given you'll still have to type '-' as the filename, but README says "Usage: xdot.py [file]", which is a bit confusing. Maybe "Usage: xdot.py (filename | - )" is better. Otherwise we can just modify the code so that we don't need the hyphen.

**Comment by jrfonseca** [comment]
Unfortunately one can't reliably omit the hyphen, as there's no way to detect when stdin will have a graph: stdin might not be a tty, but still not have pipe, as often is the case when starting xdot from application menu.

But I've fixed the instructions as suggested.
