### ISSUE TITLE
Not able to run xdot

### ISSUE THREAD

**Issue by AdityaMisra** [jrfonseca/xdot.py#62]
System -
`ProductName:	Mac OS X`
`ProductVersion:	10.13.6`

cmd1 ->`brew install xdot`
cmd2 -> `xdot`
o/p cmd2 ->
`/usr/local/bin/xdot: /usr/local/Cellar/xdot/0.9_3/libexec/bin/xdot: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory`
`/usr/local/bin/xdot: line 2: /usr/local/Cellar/xdot/0.9_3/libexec/bin/xdot: Undefined error: 0`

**Comment by jrfonseca** [comment]
I'm not responsible for the homebrew packages, so I'm afraid you'll need to report the issue directly homebrew.

**Comment by jrfonseca** [comment]
At a glance the issue is that python 3.7 was not installed in the expected location.
