### ISSUE TITLE
Missing tooltip when hovering

### ISSUE THREAD

**Issue by mihaigalos** [jrfonseca/xdot.py#71]
Using a node's `tooltip` attribute does not show a tooltip when hovering with the mouse over the node. This is looks like a bug in xdot, since exporting a `dot` file to `svg` and reading it in with a browser _does_ show the tooltip.

**Comment by jrfonseca** [comment]
Per https://www.graphviz.org/doc/info/attrs.html tooltips attributes aren't supported universally.

I just checked doing `dot -T xdot tests/graphs/url.gv` that xdot doesn't include any rendering nodes for tooltips, but it preserves the original `*tooltip` attributes.

So `xdot.py` could indeed use the `*tooltip` attributes to render GTK tooltips.

I'm afraid I don't have the time/interest to pursue this enhancement myself, but I'd be happy to merge a PR if anybody wants to give it a shot.

**Comment by mihaigalos** [comment]
@jrfonseca : I looked at the code, I see you're using PyCairo to draw shapes. Since these shapes are all on a canvas and aren't actual widgets, how would one add a tooltip?
