### ISSUE TITLE
missing self.consume()

### ISSUE THREAD

**Issue by sunziping2016** [jrfonseca/xdot.py#74]
https://github.com/jrfonseca/xdot.py/blob/6248c81c21a0fe825089311b17f2c302eea614a2/xdot/dot/parser.py#L357
It seems `self.consume()` is missing after this line. This may cause infinite loop. But as `xdot` never generate edge like `a -> b -> c`, it works now.

**Comment by jrfonseca** [comment]
Quite right again. Thanks!
