### ISSUE TITLE
Fonts don't scale on macOS

### ISSUE THREAD

**Issue by thekswenson** [jrfonseca/xdot.py#80]
I installed all dependencies using homebrew and pip.
Opening sample.py on macOS shows a graph with a font that has not been scaled properly:

![Screen Shot 2020-06-25 at 14 21 05](https://user-images.githubusercontent.com/9959942/85719360-a468ec00-b6ef-11ea-923b-5327abb86ed1.png)

**Comment by thekswenson** [comment]
I can print out the supported fonts with:
```
                font_map = PangoCairo.font_map_get_default()
                print([f.get_name() for f in font_map.list_families()])
```
There is no font name "Times-Roman" which seems to be the one hardcoded in the Pen class. There does exist "Times" and "Times New Roman".

**Comment by thekswenson** [comment]
Strangely, if I change the font to something that is known, like "Comic Sans MS", I still have the scaling issue:

![Screen Shot 2020-06-25 at 15 47 50](https://user-images.githubusercontent.com/9959942/85732133-6a9de280-b6fb-11ea-8bdf-21ddbd578232.png)

**Comment by thekswenson** [comment]
I've reported a bug [here](https://gitlab.gnome.org/GNOME/pango/-/issues/488) at the pango project.

**Comment by thekswenson** [comment]
This is a bug in pangocairo.
See this issue: https://gitlab.gnome.org/GNOME/pango/-/issues/488

**Comment by jrfonseca** [comment]
@thekswenson thank you very much for reporting the issue and narrowing it down!  Cheers.
