### ISSUE TITLE
Search function should also search in subgraph labels

### ISSUE THREAD

**Issue by yurivict** [jrfonseca/xdot.py#90]
Currently it only searches through node labels.
There is no easy way to find a subgraph when there are many of them.

xdot-1.2

**Comment by tlk** [comment]
Example graph with subgraph labels "Example", "WP01: LIRUM" and "WP02: LARUM".

```
digraph G {
    rankdir="LR";
    node [style=filled,fillcolor=white];

    START -> aaaa;
    START -> dddd;

    subgraph cluster_container {
        style="rounded,filled";
        fillcolor="#eeeeee";
        label="Example";

        subgraph cluster_first {
            style="rounded,filled";
            label="WP01: LIRUM";
            fillcolor="#eeffee";
            
            aaaa -> bbbb -> cccc;
        }

        subgraph cluster_second {
            style="rounded,filled";
            label = "WP02: LARUM";
            fillcolor="#eeffff";

            dddd -> eeee -> ffff;
        }

    }
}
```

**Comment by tlk** [comment]
This is what it looks like searching for subgraph labels after applying PR #114.

![issue_90_example1](https://github.com/jrfonseca/xdot.py/assets/90870/5435da25-08d9-4daf-80cc-5c8d6e614fcd)

![issue_90_example2](https://github.com/jrfonseca/xdot.py/assets/90870/04368ceb-5175-4573-b935-0a8034ede186)

**Comment by jrfonseca** [comment]
Fixed by https://github.com/jrfonseca/xdot.py/pull/114
