### ISSUE TITLE
Show tooltip when mouse moves above object.

### ISSUE THREAD

**Issue by dosmanak** [jrfonseca/xdot.py#91]
I'd welcome the support of tooltips in xdot similar to SVG output.
/enhancement

**Comment by jtojnar** [comment]
Tooltips were added in https://github.com/jrfonseca/xdot.py/commit/c48b4e784554c4174fc7ad9adbf371b8fe0e67f2. Though they are still somewhat wonky. #100 should fix that.

**Comment by jrfonseca** [comment]
Closing then.

**Comment by jrfonseca** [comment]
Closing then.
