### ISSUE TITLE
Ignore empty nodes

### ISSUE THREAD

**Issue by notEvil** [jrfonseca/xdot.py#94]
Hi,

for

```dot
digraph {
  {
    node [ shape=box ]
    a
    b
  }
  {
    a -> b
  }
}
```

the second subgraph contains empty node definitions (`a;` and `b;`) that replace the previous nodes here
https://github.com/jrfonseca/xdot.py/blob/6f0a5cc9c64fb18b4330c767c4d1d173c10f9bcf/xdot/dot/parser.py#L495
As a consequence, node highlights on edge hover are broken because the edge links to empty nodes. Maybe add
```python
        if id in self.node_by_name.keys():
            return
```
at the top of `handle_node`?

**Comment by jrfonseca** [comment]
Good point.  Thanks.
