### ISSUE TITLE
GUI search text box size restriction too short

### ISSUE THREAD

**Issue by sogartar** [jrfonseca/xdot.py#99]
The GUI tool text box to find a node supports only 20 characters. This is way too short. I don't see a reason it should be restricted that much.
It is also too small visually.

**Comment by jrfonseca** [comment]
Fair enough.  Could you submit a PR?

**Comment by pfez** [comment]
I was bothered by the same thing. I went ahead and submitted a PR: https://github.com/jrfonseca/xdot.py/pull/102

**Comment by jrfonseca** [comment]
Fixed.
